/**
 * Turn the hand-drawn source art in `assets/doodles/` into web assets.
 *
 * Every piece is black line work, so the drawing is entirely carried by how
 * dark each pixel is. We throw the colour away and keep that darkness as the
 * alpha channel, which gives one file that can be used as a CSS mask: the ink
 * colour then comes from a CSS variable, so a single asset serves the light
 * theme, the dark theme, an accent tint and the pale wash behind the landing
 * headline — with no second copy to keep in step.
 *
 * Deriving alpha from darkness also normalises the sources, which are not
 * consistent: most are drawn on transparency but `my-tasks.png` arrived on an
 * opaque near-white background, and as a mask that would have painted a solid
 * square. Flattening onto white first makes both kinds come out the same.
 *
 *   npm run gen:doodles
 */
import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = process.cwd();
const SRC = join(ROOT, "assets/doodles");
const OUT = join(ROOT, "public/brand/doodles");

/** Square icons. Legible from ~26px; the busier ones want 34px and up. */
const ICONS = ["today", "my-tasks", "my-tasks-2", "calendar", "projects", "search", "profile", "settings"] as const;
/** The full-body mascot, used large and pale behind the landing headline. */
const MASCOT = "landing";

/**
 * Paper is not pure white — `my-tasks.png` is drawn on #F8F8F8, which would
 * otherwise leave a faint but very visible wash of alpha across the whole
 * square. Anything at least this pale is background; what survives is
 * stretched back out so the ink itself keeps its full strength.
 */
const PAPER = 28;

/**
 * Black pixels, transparent everywhere else — ink darkness becomes alpha.
 * Returns a PNG buffer still at the source resolution.
 */
async function toMask(file: string) {
  const { data, info } = await sharp(file)
    .ensureAlpha()
    .flatten({ background: "#ffffff" }) // transparent and white both become white
    .greyscale()
    .toColourspace("b-w")
    .raw()
    .toBuffer({ resolveWithObject: true });

  const pixels = info.width * info.height;
  const rgba = Buffer.alloc(pixels * 4);
  for (let i = 0; i < pixels; i += 1) {
    const ink = 255 - data[i * info.channels];
    // rgb stays 0 (black); the mask consumer only ever reads alpha.
    rgba[i * 4 + 3] = ink <= PAPER ? 0 : Math.round(((ink - PAPER) / (255 - PAPER)) * 255);
  }

  return sharp(rgba, { raw: { width: info.width, height: info.height, channels: 4 } })
    .png()
    .toBuffer();
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const written: string[] = [];

  for (const name of ICONS) {
    // Trim the empty margin first so every icon fills its box by the same
    // amount — the sources are padded inconsistently, which at icon sizes
    // reads as some of them simply being smaller than the others.
    const base = sharp(await toMask(join(SRC, `${name}.png`))).trim({ threshold: 8 });

    for (const size of [128, 256]) {
      const file = size === 256 ? `${name}.png` : `${name}-128.png`;
      const info = await base
        .clone()
        .resize(size, size, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .png({ palette: true, effort: 10 })
        .toFile(join(OUT, file));
      written.push(`${file} ${(info.size / 1024).toFixed(0)}kb`);
    }
  }

  const info = await sharp(await toMask(join(SRC, `${MASCOT}.png`)))
    .trim({ threshold: 8 })
    .resize({ width: 900, withoutEnlargement: true })
    .png({ palette: true, effort: 10 })
    .toFile(join(OUT, "mascot.png"));
  written.push(`mascot.png ${(info.size / 1024).toFixed(0)}kb`);

  await writeFile(
    join(OUT, "README.txt"),
    [
      "Generated by `npm run gen:doodles` from assets/doodles/.",
      "",
      "Black-on-transparent line art where the alpha channel *is* the drawing.",
      "Used as CSS mask-image so the colour comes from CSS and one file serves",
      "both themes — see <Doodle> in src/components/Doodle.tsx. Editing these",
      "by hand is pointless; edit the source art and re-run the script.",
      "",
    ].join("\n"),
  );

  console.log("doodles written:\n  " + written.join("\n  "));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
