/** Shared by initialize, every run context, and the copyable triage prompt. */
export const ACTION_GUIDANCE = `Prepare actions before reporting the list ready:

- Read houseRules.writeDrafts on every run. The draft-preparation steps below apply only when enabled or explicitly requested by the user. A disabled setting does not prevent repairing source links.
- Gmail: fetch the actual message and its threadId, RFC Message-ID, subject, and mailbox address. Send source.threadId and source.account on every mail task. A Gmail message id or draft id is not a thread id. Never substitute a generic inbox or a search page for the exact conversation.
- Verify each mailbox through that mail connector's account/profile or the authenticated mailbox UI. ToDo's user.email is the app login, NOT evidence of the mailbox containing a message. Never copy it into source.account or draft.account by default. With multiple mailboxes, keep each message ID, thread ID and draft ID paired with the account that returned it; a 404 in one mailbox does not mean the email was deleted. Find the correct account and read the item there before repairing the task.
- Outlook: preserve the provider's webLink in source.url and the default Graph message id in source.externalId. Keep the mailbox in source.account. Use the provider URL instead of inventing a desktop Outlook scheme.
- A reply must be saved INSIDE its source conversation. Gmail requires message.threadId plus In-Reply-To and References headers and a matching Subject; use the connector's equivalent threaded-reply operation (for example reply_message_id) if it sets these for you. Outlook requires createReply/createReplyAll on the source message, followed by updating the draft body. Creating a new unrelated message does not satisfy a reply task.
- Read the saved draft back using the mail connector. Check draft state (Gmail DRAFT label / Outlook isDraft), recipient, mailbox, subject, body, and conversation. Ensure the composed response is present, not just an empty editor with quoted original mail. Only then supply draft.externalId and draft.verifiedAt (the read-back time), draft.account, and Gmail draft.threadId or Outlook draft.replyToId (the source id used for createReply). verificationMethod defaults to provider_api. ToDo stores references; attach_draft does not save mail in Gmail or Outlook.
- If an authenticated Gmail mailbox UI is available, a reply/reply_all may instead use verificationMethod=mailbox_ui after reopening the persisted draft from Drafts or its source thread. Check the actual mailbox, recipient, subject, composed body, and matching conversation. Explicitly provide account, threadId, to, subject, body, and verifiedAt; omit externalId because the API draft id is unknown. Suggested text, a link, an empty editor, or a composer that has not been reopened is not this verification. Do not claim API verification or invent an id. This exception does not cover Outlook or forward/new delegation drafts.
- For delegation, read the current team roster and use the exact delegateTo name. Prepare a forward/new draft addressed to that person's email, with subject and enough original context to act. Store draft.to and the draft's OWN threadId/account, which may differ from the original. An original mailbox permalink may be inaccessible to the delegate: include the relevant context and attachments when available. Never send the handoff yourself.
- Reuse the existing draft.externalId returned in get_run_context/get_task. For a mailbox_ui reference with no API id, find the existing draft through the mailbox and thread (list drafts/read the conversation) before making or editing anything. Read it before making another draft, preserve edits the user made, and update the existing draft only when appropriate. If it has been sent, verify that evidence before completing the task; if deleted, do not claim it is still ready. Use detach_draft after confirming a draft was sent or deleted to clear its stale reference without removing the task. A temporary connector error is not proof of deletion.
- If the connector cannot create a threaded draft, provide suggested body text without verifiedAt and clearly report the missing capability. Do not invent provider ids, saved-draft URLs, or a successful save. Choosing an unprepared delegate in ToDo opens a prefilled composer; it does not prove a saved draft or a sent email.
- Outlook meeting invitations: retain the invite EMAIL as source so the user can review Accept/Decline in Outlook on phone or desktop. Add a separate calendar link with kind=calendar, provider=outlook_calendar, the event's OWN externalId and Graph webLink. Add the Teams meeting join URL separately with kind=join. A join link is not an RSVP. For Teams messages use the exact message permalink, including tenant and conversation context.
- Never draft a claim that a payment, attachment, approval, or other action already happened without evidence. If a prerequisite is unfinished, say so in the task and use conditional wording or a clear placeholder in the suggested response. Sending, payment, and RSVP remain the user's actions.
- Read actionIssues and linkGaps. Repair missing ids and drafts in the same run using sync_tasks with replace=none or attach_draft, then re-read the task. Do not report an action as ready while a gap remains. If a connector was unavailable or the sweep is incomplete, preserve the existing list with replace=none and report the coverage gap; never remove tasks just because their source could not be checked.`;
